name: 'Update Relisio Product Portfolio'
description: 'Create/Update a Relisio product from GitHub'
inputs:
    relisio-url:
        description: 'Relisio base url (only for enterprise installations)'
        default: 'https://relisio.com'
        required: false
    api-key:
        description: 'API key to authorize the deployment'
        required: true
    workspace-path:
        description: 'Path of the Workspace where to publish the Product'
        required: true
    product-template-id:
        description: 'ID of an existing product withing the workspace to clone as the base for this new product'
        required: false
    product-id:
        description: 'ID of an existing product (only if you want to update the existing product)'
        required: false
    product-name:
        description: 'Name of the product'
        required: true
    visibility:
        description: 'Visibility of the product withing the workspace (private, internal or public)'
        required: true
        default: 'internal'
outputs:
    product-id:
        description: 'ID of the Deployed Product'
    public-url:
        description: 'URL of the Deployed Product'
branding:
    icon: 'relisio-logo.svg'
    color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
